name: ci

on:
  workflow_dispatch: {}
  schedule:
    - cron: 30 12 * * 1
  push:
    paths:
      - Dockerfile
      - start.sh
      - cli.sh
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        version: ["stable", "develop", "v2.5.0"]
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: docker.super.fish
          username: robot$pleroma+ci
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: docker.super.fish/pleroma/pleroma

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            PLEROMA_VERSION=${{ matrix.version }}
          context: .
          file: ./Dockerfile
          tags: docker.super.fish/pleroma/pleroma:${{ matrix.version }}
          labels: ${{ steps.meta.outputs.labels }}
